### PR TITLE
Update to Calico v0.2.0-RC2

### PR DESCRIPTION
**Pull request by armanbilge**
Built the website locally and took a quick walkthrough, nothing is obviously broken 😅 

Thanks for all your feedback! Some of it went into this release.

### CODE REVIEW

**Comment by yurique** [comment]
oh wow, I totally missed this (was out of town for a week) :)

**Comment by yurique** [comment]
and of course I only saw this after doing it myself (should get published soon)

**Comment by armanbilge** [comment]
Oh, so we can just close this one? :)

**Comment by yurique** [comment]
it's a NOOP now :)

**Comment by yurique** [comment]
`0.17.0-M3` is out

**Pull request closed without merging**
